function [ ] = plotVelocity( run, plotTime )
% extract velocity 
    y1 = run.Data.Analog( 3, plotTime );
    y2 = run.Data.Analog( 4, plotTime );

    vXcolor = [ 90 145 255 ] ./ 255;
    vYcolor = [ 255 145 90 ] ./ 255;

    x = 1 : numel( plotTime );

    Plot.patchline( x, y1, ...
                        'LineWidth', 4, ...
                    'edgeColor', vXcolor, ...
                    'edgeAlpha', 0.8, ...
                    'faceAlpha', 0.0, ...
                    'MarkerSize', 8, ...
                    'MarkerFaceColor', 'k', ...
                    'MarkerEdgeColor', 'k', ...
                    'AlignVertexCenters', 'off' )
    hold on
    Plot.patchline( x, y2, ...
                    'LineWidth', 4, ...
                    'edgeColor', vYcolor, ...
                    'edgeAlpha', 0.8, ...
                    'faceAlpha', 0.0, ...
                    'MarkerSize', 8, ...
                    'MarkerFaceColor', 'k', ...
                    'MarkerEdgeColor', 'k', ...
                    'AlignVertexCenters', 'off' )
end
