function [] = plotPred( run, pred, plotTime, type, color, opacity, lineStyle, step )
    addpath( '/snel/home/lwimala/bin/analysis_tools/' )
    [ x, y ] = Cherian.utils.determinePredType( pred, run, type, plotTime );
    if ~strcmp( type, 'pos')
        % plot dotted line 
        Plot.patchline( x, y, ...
                        'LineWidth', 4, ...
                        'LineStyle', lineStyle, ...
                        'edgeAlpha', opacity, ...
                        'edgeColor', color, ...
                        'faceAlpha', 0.0, ...
                        'faceColor', color, ...
                        'AlignVertexCenters', 'off' )
        % plot low opacity line over top to add continuity 
        if strcmp( lineStyle, ':' ) || strcmp( lineStyle, '--' )
            Plot.patchline( x, y, ...
                            'LineWidth', 4, ...
                            'LineStyle', '-', ...
                            'edgeAlpha', 0.5, ...
                            'edgeColor', color, ...
                            'faceAlpha', opacity-0.2, ...
                            'faceColor', color, ...
                            'AlignVertexCenters', 'off' )
        end % if strcmp
    else
        x = x( 1, : );
        y = y( 1, : );
        u = x( 2, : );
        v = y( 2, : );
        quiver( x( 1:step:end ), y( 1:step:end ), u( 1:step:end ), v( 1:step:end ), ...
                'Color', color, ...
                'LineWidth', 4, ...
                'ShowArrowHead', 'on', ...
                'MaxHeadSize', 0.3, ...
                'AutoScaleFactor', 0.5 )
        hold on
        Plot.patchline( x, y, ...
                        'LineStyle', lineStyle, ...
                        'LineWidth', 4.5, ...
                        'edgeColor', color, ...
                        'edgeAlpha', 0.7, ...
                        'faceAlpha', 0.0, ...
                        'MarkerSize', 8, ...
                        'MarkerFaceColor', 'k', ...
                        'MarkerEdgeColor', 'k', ...
                        'AlignVertexCenters', 'off' )
        if strcmp( lineStyle, ':' ) || strcmp( lineStyle, '--' )
            Plot.patchline( x, y, ...
                            'LineWidth', 4.5, ...
                            'LineStyle', '-', ...
                            'edgeAlpha', 0.25, ...
                            'edgeColor', color, ...
                            'faceAlpha', opacity-0.1, ...
                            'faceColor', color, ...
                            'AlignVertexCenters', 'off' )
        end % if strcmp

    end
end
