function [ ] = plotEMG( run, plotTime )

    emgColors = { [ 255 90 90 ], ...
                  [ 220 77 255 ], ...
                  [ 90 90 255 ], ...
                  [ 77 255 172 ], ...
                  [ 77 232 255 ], ...
                  [ 249 224 64 ], ...
                  [ 253 174 56 ], ...
                  [ 228 18 18 ], ...
                  [ 28 161 255 ], ...
                  [ 18 186 228 ] };
    offset = 5;
    opacity = 0.7;
    
    x = 1 : numel( plotTime );
    for i = 1:2:10
        % extract EMG channel
        y = run.Data.Analog( i + offset, plotTime );
        y = y ./ mean( y );
        % calculate color
        color = emgColors{ i } ./ 255;


        Plot.patchline( x, y, ...
                        'LineWidth', 4, ...
                        'edgeColor', color, ...
                        'edgeAlpha', opacity, ...
                        'faceAlpha', 0.0, ...
                        'MarkerSize', 8, ...
                        'MarkerFaceColor', 'k', ...
                        'MarkerEdgeColor', 'k', ...
                        'AlignVertexCenters', 'off' )
        hold on
    end
end
