function [ ] = plotTarget( x, y, color )
    Plot.patchline( x, y, ...
                    'LineStyle', 'none', ...
                    'Marker', 'square', ....
                    'MarkerSize', 50, ...
                    'MarkerEdgeColor', color./255, ...
                    'MarkerFaceColor', color./255, ...
                    'faceAlpha', 0.3, ... 
                    'edgeAlpha', 0.3 )
end
